version: 4.5.0
gitURI: https://github.com/Z3Prover/z3
gitTag: 'z3-#{version}'
gitWorkdir: 'z3-#{version}'
cPrefacePrimary: |
  #include <stdio.h>
  #include "#{path}/z3_macros.h"
cPrefaceRest: |
  #include <stdio.h>
  #include "#{path}/z3_macros.h"
  #include "#{path}/z3_api.h"
hscPreface: |
  {-# OPTIONS_GHC -fno-warn-unused-imports #-}
  #include <bindings.dsl.h>
  #include "z3_macros.h"
  #include "z3_api.h"
  #include "#{header}"
  module #{module} where
  import Foreign.Ptr
  #strict_import
headersPath: 'z3-#{version}/src/api'
headers:
  - z3_api.h
  - z3_algebraic.h
  - z3_ast_containers.h
  - z3_fixedpoint.h
  - z3_fpa.h
  - z3_interp.h
  - z3_optimization.h
  - z3_polynomial.h
  - z3_rcf.h
headerOutputPath: '#{header}.hsc'
substitutions:
  - type: ccall
    name: Z3_error_handler
    newType: callback_t
